#!/usr/bin/env python3
"""Generate the contract field reference from the schemas bundled in the CLI.

The pages under ``docs/reference/`` are not written by hand. They are rendered
from the JSON Schema files that ship inside the pinned ``data-product-forge``
package (``fluid_build/schemas/fluid-schema-<version>.json``), the same files
``fluid validate`` checks a contract against. There is no second copy of the
schema in this repo to drift from.

Output (``--out-dir``, default ``docs/reference/``):

* ``contract-<stable>.md``          every field of the newest stable schema
* ``contract-<preview>-preview.md`` field-by-field delta of each preview schema
                                    against that stable schema

Which version is stable and which is preview is read from the CLI itself
(``FluidSchemaManager.latest_bundled_version`` and ``PREVIEW_VERSIONS``), so a
promotion in a later CLI release changes the output instead of leaving a stale
claim behind.

Usage::

    python scripts/gen_contract_reference.py            # (re)write the pages
    python scripts/gen_contract_reference.py --check    # exit 1 if they drifted

``--check`` writes nothing. It fails when a committed page differs from what the
installed CLI would generate, when an expected page is missing, or when a page
carrying the generated marker is no longer expected (a stale leftover).

The installed CLI must be the version pinned in ``docs/.vuepress/cli-version.json``;
the pages say which package version they came from, so rendering them from any
other version would make that line untrue. The walker refuses schema keywords it
does not know how to render rather than dropping them silently.

Output is byte-stable: same installed schemas in, same bytes out. Nothing reads
the clock, the environment or the network.
"""

from __future__ import annotations

import argparse
import difflib
import hashlib
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parent.parent
VERSION_FILE = REPO_ROOT / "docs" / ".vuepress" / "cli-version.json"
DEFAULT_OUT_DIR = REPO_ROOT / "docs" / "reference"

MARKER = "<!-- generated by scripts/gen_contract_reference.py; do not edit by hand -->"
SPEC_SITE = "https://open-data-protocol.github.io/fluid/"
PACKAGE = "data-product-forge"

# Keywords the walker renders. Anything else in a schema is a hard error, so a
# new release that adds (say) patternProperties cannot be silently misdocumented.
KNOWN_KEYWORDS = {
    "$comment", "$defs", "$id", "$ref", "$schema", "additionalProperties",
    "allOf", "anyOf", "const", "default", "dependentRequired", "description",
    "enum", "errorMessage", "examples", "format", "if", "items", "maximum",
    "minItems", "minLength", "minimum", "not", "oneOf", "pattern", "properties",
    "propertyNames", "required", "then", "title", "type", "uniqueItems",
}
# Keywords whose value is data or a name->schema map, not a schema to audit.
DATA_KEYWORDS = {"examples", "enum", "const", "default", "dependentRequired", "required"}
MAP_KEYWORDS = {"properties", "$defs"}

# A top-level section with more rows than this is split into one table per
# second-level field, each under its own heading.
SPLIT_ROWS = 40
# Constraint text longer than this is folded into a <details> element so a
# 1,000-character pattern does not stretch the table.
FOLD_CHARS = 140
# A definition expanded at more than one path is listed in full once if it
# produced at least this many rows; later paths point back to the first.
SHARE_MIN_ROWS = 20


# --------------------------------------------------------------------------- #
# Loading from the installed CLI
# --------------------------------------------------------------------------- #


def die(message: str, code: int = 2) -> "None":
    print(f"ERROR: {message}", file=sys.stderr)
    sys.exit(code)


@dataclass(frozen=True)
class Source:
    cli_version: str
    stable: str
    previews: tuple[str, ...]
    schema_dir: Path
    versions: tuple[str, ...]


def load_source() -> Source:
    try:
        import fluid_build  # type: ignore
        from fluid_build.schema_manager import FluidSchemaManager  # type: ignore
        from importlib import metadata
    except ImportError as exc:  # pragma: no cover - environment problem
        die(
            f"cannot import the fluid_build package ({exc}). Install the pinned CLI first: "
            "pip install data-product-forge==<supportedCliVersion>"
        )
    pin = json.loads(VERSION_FILE.read_text(encoding="utf-8"))["supportedCliVersion"]
    installed = metadata.version(PACKAGE)
    if installed != pin:
        die(
            f"installed {PACKAGE} is {installed} but docs/.vuepress/cli-version.json pins {pin}. "
            "The generated pages name the package version they came from, so install the pinned "
            f"version: pip install {PACKAGE}=={pin}"
        )
    schema_dir = Path(fluid_build.__file__).resolve().parent / "schemas"
    bundled = tuple(FluidSchemaManager.BUNDLED_VERSIONS)
    previews = tuple(v for v in bundled if v in FluidSchemaManager.PREVIEW_VERSIONS)
    return Source(
        cli_version=installed,
        stable=FluidSchemaManager.latest_bundled_version(),
        previews=previews,
        schema_dir=schema_dir,
        versions=bundled,
    )


def load_schema(src: Source, version: str) -> tuple[dict[str, Any], str]:
    path = src.schema_dir / f"fluid-schema-{version}.json"
    raw = path.read_bytes()
    schema = json.loads(raw.decode("utf-8"))
    audit_keywords(schema, f"fluid-schema-{version}.json", "$")
    return schema, hashlib.sha256(raw).hexdigest()


def audit_keywords(node: Any, where: str, path: str) -> None:
    if isinstance(node, list):
        for i, item in enumerate(node):
            audit_keywords(item, where, f"{path}[{i}]")
        return
    if not isinstance(node, dict):
        return
    for key, value in node.items():
        if key not in KNOWN_KEYWORDS:
            die(
                f"{where} {path}: keyword {key!r} is not one the reference generator renders. "
                "Teach scripts/gen_contract_reference.py about it before regenerating."
            )
        if key in DATA_KEYWORDS:
            continue
        if key in MAP_KEYWORDS:
            for name, sub in value.items():
                audit_keywords(sub, where, f"{path}.{key}.{name}")
        elif key == "additionalProperties" and isinstance(value, bool):
            continue
        else:
            audit_keywords(value, where, f"{path}.{key}")


# --------------------------------------------------------------------------- #
# Text helpers
# --------------------------------------------------------------------------- #

_CODE_SPAN = re.compile(r"(`+)(.+?)\1", re.S)


def code(text: str) -> str:
    """A markdown code span that survives table cells."""
    text = text.replace("|", "\\|").replace("\n", " ")
    fence = "``" if "`" in text else "`"
    pad = " " if text.startswith("`") or text.endswith("`") else ""
    return f"{fence}{pad}{text}{pad}{fence}"


def html_code(text: str) -> str:
    """A raw <code> element (used inside <details>, where markdown does not run)."""
    esc = (
        text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        .replace("{", "&#123;").replace("}", "&#125;").replace("|", "&#124;")
    )
    return f"<code>{esc}</code>"


def _escape_plain(text: str) -> str:
    out = text.replace("\\", "\\\\")
    for ch in ("<", ">"):
        out = out.replace(ch, "&lt;" if ch == "<" else "&gt;")
    out = out.replace("{{", "&#123;&#123;").replace("}}", "&#125;&#125;")
    out = out.replace("|", "\\|").replace("*", "\\*").replace("[", "\\[").replace("]", "\\]")
    return out


def prose(text: str) -> str:
    """Schema description -> one table-cell-safe line of markdown.

    Backtick spans pass through (their pipes are escaped); everything outside
    them is escaped so a stray ``<exposeId>`` or ``*`` cannot become HTML or
    emphasis and a ``{{`` cannot reach the Vue template compiler.
    """
    pieces: list[str] = []
    last = 0
    for match in _CODE_SPAN.finditer(text):
        pieces.append(_escape_plain(text[last:match.start()]))
        pieces.append(code(match.group(2).strip()))
        last = match.end()
    pieces.append(_escape_plain(text[last:]))
    joined = "".join(pieces).strip()
    return re.sub(r"[ \t]*\n[ \t]*", "<br>", joined)


def join_path(parent: str, key: str) -> str:
    return key if not parent else f"{parent}.{key}"


def fold(summary: str, items: list[str]) -> str:
    """Fold a long list of <code> items behind a <details> summary."""
    return f"<details><summary>{summary}</summary>{' '.join(html_code(i) for i in items)}</details>"


# --------------------------------------------------------------------------- #
# The schema walker
# --------------------------------------------------------------------------- #


@dataclass
class Row:
    path: str
    type: str
    required: bool
    constraints: list[str] = field(default_factory=list)  # markdown lines
    default: str | None = None
    description: str = ""
    when: str | None = None  # condition text for rows that exist only under an `if`
    notes: list[str] = field(default_factory=list)  # conditional constraints (markdown)

    @property
    def key(self) -> tuple[str, str]:
        return (self.path, self.when or "")

    def signature(self) -> dict[str, Any]:
        return {
            "type": self.type,
            "required": self.required,
            "allowed values": self.constraints + self.notes,
            "default": self.default,
            "description": self.description,
        }


class Walker:
    def __init__(self, schema: dict[str, Any]):
        self.schema = schema
        self.defs: dict[str, Any] = schema.get("$defs", {})
        self.rows: list[Row] = []
        self.index: dict[tuple[str, str], Row] = {}
        self.shared: dict[str, tuple[str, int]] = {}

    # -- resolution ---------------------------------------------------------

    def resolve(self, node: Any) -> dict[str, Any]:
        if not isinstance(node, dict):
            die(f"unexpected non-object schema node: {node!r}")
        guard = 0
        while "$ref" in node:
            guard += 1
            if guard > 64:
                die("$ref chain too deep (cycle?)")
            ref = node["$ref"]
            if not ref.startswith("#/$defs/"):
                die(f"non-local $ref {ref!r} is not supported")
            target = self.defs.get(ref[len("#/$defs/"):])
            if target is None:
                die(f"dangling $ref {ref!r}")
            sibling = {k: v for k, v in node.items() if k != "$ref"}
            node = {**target, **sibling}
        return node

    def alts(self, eff: dict[str, Any]) -> list[dict[str, Any]]:
        out: list[dict[str, Any]] = []
        for kw in ("anyOf", "oneOf"):
            for alt in eff.get(kw, []):
                out.append(self.resolve(alt))
        return out

    # -- types --------------------------------------------------------------

    def type_names(self, eff: dict[str, Any]) -> list[str]:
        names: list[str] = []

        def add(name: str) -> None:
            if name not in names:
                names.append(name)

        def one(e: dict[str, Any]) -> None:
            t = e.get("type")
            ts = list(t) if isinstance(t, list) else ([t] if t else [])
            if not ts:
                if "properties" in e or "additionalProperties" in e:
                    ts = ["object"]
                elif "items" in e:
                    ts = ["array"]
                elif "enum" in e:
                    ts = sorted({_py_type(v) for v in e["enum"]})
                elif "const" in e:
                    ts = [_py_type(e["const"])]
            for name in ts:
                if name == "array":
                    items = e.get("items")
                    add(f"array of {self.type_label(self.resolve(items))}" if isinstance(items, dict) else "array")
                elif name == "object":
                    add(self.object_label(e))
                else:
                    add(name)

        one(eff)
        for alt in self.alts(eff):
            one(alt)
        return names

    def type_label(self, eff: dict[str, Any]) -> str:
        names = self.type_names(eff)
        # inside "array of ...", spell objects plainly
        names = ["object" if n.startswith("object") else n for n in names]
        return " or ".join(names) if names else "any"

    def object_label(self, e: dict[str, Any]) -> str:
        ap = e.get("additionalProperties", None)
        has_props = bool(e.get("properties"))
        if isinstance(ap, dict):
            return "object (map)"
        if ap is False:
            return "object"
        return "object (open)" if has_props else "object (free-form)"

    # -- constraints --------------------------------------------------------

    def constraint_lines(self, eff: dict[str, Any], *, with_alts: bool = True) -> list[str]:
        """Constraint prose for one resolved schema (no recursion into properties)."""
        lines: list[str] = []
        if "enum" in eff:
            lines.append(_enum_line(eff["enum"]))
        if "const" in eff:
            lines.append(f"must be {code(_scalar(eff['const']))}")
        if "pattern" in eff:
            lines.append(_pattern_line("matches", eff["pattern"]))
        if "format" in eff:
            lines.append(f"format {code(eff['format'])}")
        if "minLength" in eff:
            lines.append(f"min length {eff['minLength']}")
        if "minimum" in eff:
            lines.append(f"min {eff['minimum']}")
        if "maximum" in eff:
            lines.append(f"max {eff['maximum']}")
        if "minItems" in eff:
            lines.append(f"min items {eff['minItems']}")
        if eff.get("uniqueItems"):
            lines.append("unique items")
        if "not" in eff:
            neg = self.resolve(eff["not"])
            if set(neg) == {"pattern"}:
                lines.append(_pattern_line("must not match", neg["pattern"]))
            else:
                die(f"unsupported `not` schema: {neg!r}")
        items = eff.get("items")
        if isinstance(items, dict):
            lines.extend("each item: " + t for t in self.constraint_lines(self.resolve(items)))
        if "propertyNames" in eff:
            pn = self.resolve(eff["propertyNames"])
            lines.extend("keys: " + t for t in self.constraint_lines(pn))
        for dep_key, dep_vals in eff.get("dependentRequired", {}).items():
            lines.append(
                f"if {code(dep_key)} is set, {', '.join(code(v) for v in dep_vals)} "
                f"{'is' if len(dep_vals) == 1 else 'are'} required"
            )
        if with_alts:
            alts = self.alts(eff)
            only_required = [a for a in alts if set(a) == {"required"}]
            if only_required:
                lines.append(
                    "at least one of "
                    + " or ".join("/".join(code(k) for k in a["required"]) for a in only_required)
                    + " is required"
                )
            typed: list[tuple[str | None, list[str]]] = []
            for alt in alts:
                if set(alt) == {"required"} or "properties" in alt:
                    continue
                alines = self.constraint_lines(alt, with_alts=False)
                if alines:
                    declared = alt.get("type")
                    label = " or ".join(declared) if isinstance(declared, list) else declared
                    typed.append((label, alines))
            if typed:
                if len({t for t, _ in typed if t}) <= 1:
                    flat = [line for _, ls in typed for line in ls]
                    lines.append(flat[0])
                    lines.extend("or " + line for line in flat[1:])
                else:
                    lines.extend((f"{t}: " if t else "") + ", ".join(ls) for t, ls in typed)
        return lines

    def describe_schema(self, node: Any) -> str:
        """Short prose for a constraint-only schema (used for `then` overlays)."""
        eff = self.resolve(node)
        alts = self.alts(eff)
        if alts:
            return " or ".join(self.describe_schema(a) for a in alts)
        t = eff.get("type")
        if t == "array":
            items = eff.get("items")
            inner = self.describe_schema(items) if isinstance(items, dict) else "any value"
            return f"an array whose items are each {inner}"
        lead = f"a {t}" if t else "a value"
        extra = [line.replace("matches ", "matching ", 1) for line in self.constraint_lines(eff, with_alts=False)]
        return lead + (" " + " and ".join(extra) if extra else "")

    # -- conditions ---------------------------------------------------------

    def describe_if(self, node: Any) -> str:
        eff = self.resolve(node)
        parts: list[str] = []
        props = eff.get("properties", {})
        for key, sub in props.items():
            sub = self.resolve(sub)
            if "const" in sub:
                parts.append(f"{code(key)} is {code(_scalar(sub['const']))}")
            elif "pattern" in sub:
                parts.append(f"{code(key)} matches {code(sub['pattern'])}")
            else:
                die(f"unsupported `if` property schema for {key!r}: {sub!r}")
        for key in eff.get("required", []):
            if key not in props:
                parts.append(f"{code(key)} is set")
        if "not" in eff:
            neg = self.resolve(eff["not"])
            if set(neg) != {"required"}:
                die(f"unsupported `if` not-clause: {neg!r}")
            parts.extend(f"{code(k)} is not set" for k in neg["required"])
        if "anyOf" in eff:
            parts.append(" or ".join(self.describe_if(a) for a in eff["anyOf"]))
        if not parts:
            die(f"unsupported `if` schema: {eff!r}")
        return " and ".join(parts)

    # -- expansion ----------------------------------------------------------

    def add_row(self, row: Row) -> Row:
        if row.key in self.index:
            die(f"duplicate reference row {row.key!r}")
        self.rows.append(row)
        self.index[row.key] = row
        return row

    def expand(
        self, path: str, node: Any, required: bool, when: str | None, parent_desc: str = ""
    ) -> Row:
        eff = self.resolve(node)
        alts = self.alts(eff)
        desc = eff.get("description", "") or parent_desc
        alt_bits: list[str] = []
        for alt in alts:
            ad = alt.get("description")
            if ad and ad != desc:
                label = alt.get("type") or "form"
                alt_bits.append(f"{label} form: {ad}")
        row = Row(
            path=path,
            type=self.type_label_row(eff),
            required=required,
            constraints=self.constraint_lines(eff),
            default=(
                code(json.dumps(eff["default"], ensure_ascii=False)) if "default" in eff else None
            ),
            description=" ".join(x for x in [desc] + alt_bits if x),
            when=when,
        )
        self.add_row(row)
        first = self.shared_elsewhere(node, path, when)
        if first is not None:
            row.description = _append(row.description, self.same_as(first))
        else:
            self.record_shared(node, path, when, lambda: self.children(path, eff, row, when, prefix=""))
        return row

    # -- shared definitions -------------------------------------------------
    # A $defs entry that is expanded at several paths (the legacy `build` and
    # `builds[]`, the exposes under `environments.<key>`) is listed once, at its
    # first path. Later paths get one row that points back, so the page does not
    # repeat hundreds of rows and the repeats cannot disagree.

    def shared_elsewhere(self, node: Any, path: str, when: str | None) -> str | None:
        if when is not None or not isinstance(node, dict) or "$ref" not in node:
            return None
        if "properties" in node:
            return None
        seen = self.shared.get(node["$ref"])
        if seen is None or seen[0] == path or seen[1] < SHARE_MIN_ROWS:
            return None
        return seen[0]

    def record_shared(self, node: Any, path: str, when: str | None, expand_children: Any) -> None:
        before = len(self.rows)
        expand_children()
        if when is None and isinstance(node, dict) and "$ref" in node and "properties" not in node:
            self.shared.setdefault(node["$ref"], (path, len(self.rows) - before))

    @staticmethod
    def same_as(first: str) -> str:
        return f"Same fields as {code(first)}: read that section with this path as the prefix."

    def type_label_row(self, eff: dict[str, Any]) -> str:
        names = self.type_names(eff)
        return " or ".join(names) if names else "any"

    def children(
        self, path: str, eff: dict[str, Any], row: Row, when: str | None, prefix: str
    ) -> None:
        """Rows for the properties, map values and array items of `eff`."""
        variants = [eff] + [a for a in self.alts(eff) if "properties" in a]
        for var in variants:
            req = set(var.get("required", []))
            for key, sub in var.get("properties", {}).items():
                self.expand(join_path(path, key), sub, key in req, when)
            ap = var.get("additionalProperties")
            if isinstance(ap, dict):
                self.expand(join_path(path, "<key>"), ap, False, when)
        items = eff.get("items")
        if isinstance(items, dict):
            ieff = self.resolve(items)
            item_path = path + "[]"
            first = self.shared_elsewhere(items, item_path, when)
            if first is not None:
                row.description = _append(row.description, self.same_as(first))
            else:
                self.record_shared(items, item_path, when, lambda: self.children(item_path, ieff, row, when, prefix="Each item: "))
            for alt in self.alts(ieff):
                ad = alt.get("description")
                if ad and ad not in row.description:
                    row.description = _append(row.description, f"{alt.get('type', 'form')} form: {ad}")
        for entry in eff.get("allOf", []):
            self.apply_all_of(path, self.resolve(entry), row, when, prefix)

    def apply_all_of(
        self, path: str, entry: dict[str, Any], row: Row, when: str | None, prefix: str
    ) -> None:
        if "if" not in entry:
            die(f"allOf entry without `if` at {path}: {entry!r}")
        cond = self.describe_if(entry["if"])
        then = self.resolve(entry.get("then", {}))
        plain = f"When {cond}: "
        first = f"{prefix}when {cond}: " if prefix else plain
        first = first[0].upper() + first[1:]
        self.overlay(path, then, cond, row, when, first, plain)

    def overlay(
        self,
        path: str,
        then: dict[str, Any],
        cond: str,
        row: Row,
        when: str | None,
        lead: str,
        plain: str,
    ) -> None:
        """Apply a `then` schema to the rows already emitted at `path`."""
        notes: list[str] = []
        for line in self.constraint_lines(then, with_alts=True):
            notes.append(line)
        ap = then.get("additionalProperties")
        if isinstance(ap, dict):
            notes.append("each value is " + self.describe_schema(ap))
        props = then.get("properties", {})
        if then.get("required") and not props:
            notes.append("requires " + ", ".join(code(k) for k in then["required"]))
        if then.get("description") and not props:
            notes.append(then["description"])
        for line in notes:
            row.notes.append(lead + line)
        req = set(then.get("required", []))
        for key, sub in props.items():
            child_path = join_path(path, key)
            existing = self.index.get((child_path, when or ""))
            sub_eff = self.resolve(sub)
            if existing is not None and self.adds_fields(child_path, sub_eff, when):
                # the base row is a bare container; the condition decides its shape
                if sub_eff.get("description"):
                    existing.notes.append(plain + sub_eff["description"])
                creq = set(sub_eff.get("required", []))
                for ckey, csub in sub_eff.get("properties", {}).items():
                    self.expand(join_path(child_path, ckey), csub, ckey in creq, cond)
            elif existing is not None:
                self.overlay(child_path, sub_eff, cond, existing, when, plain, plain)
            else:
                self.expand(child_path, sub, key in req, cond)

    def adds_fields(self, path: str, eff: dict[str, Any], when: str | None) -> bool:
        """True when `eff` declares properties that have no row at `path` yet."""
        return any(
            (join_path(path, key), when or "") not in self.index
            for key in eff.get("properties", {})
        )

    def walk_root(self) -> list[Row]:
        req = set(self.schema.get("required", []))
        for key, sub in self.schema.get("properties", {}).items():
            self.expand(key, sub, key in req, None)
        return self.rows


def _py_type(value: Any) -> str:
    if isinstance(value, bool):
        return "boolean"
    if isinstance(value, int):
        return "integer"
    if isinstance(value, float):
        return "number"
    if isinstance(value, str):
        return "string"
    if value is None:
        return "null"
    return "object"


def _append(text: str, extra: str) -> str:
    return f"{text} {extra}" if text else extra


def _scalar(value: Any) -> str:
    return value if isinstance(value, str) else json.dumps(value, ensure_ascii=False)


def _enum_line(values: list[Any]) -> str:
    rendered = [_scalar(v) for v in values]
    inline = "one of " + ", ".join(code(r) for r in rendered)
    if len(inline) <= FOLD_CHARS:
        return inline
    return fold(f"one of {len(rendered)} values", rendered)


def _pattern_line(lead: str, pattern: str) -> str:
    inline = f"{lead} {code(pattern)}"
    if len(inline) <= FOLD_CHARS:
        return inline
    return f"{lead} <details><summary>a {len(pattern)}-character pattern</summary>{html_code(pattern)}</details>"


# --------------------------------------------------------------------------- #
# Rendering
# --------------------------------------------------------------------------- #

HEADER = "| Path | Type | Required | Allowed values | Default | Description |\n| --- | --- | --- | --- | --- | --- |"


def render_cell_constraints(row: Row, with_notes: bool = True) -> str:
    lines = list(row.constraints)
    if with_notes:
        lines.extend(row.notes)
    return "<br>".join(lines) if lines else ""


def render_row(row: Row) -> str:
    desc = prose(row.description) if row.description else ""
    if row.when:
        cond = f"Only when {row.when}."
        desc = f"{cond} {desc}".strip()
    cells = [
        code(row.path),
        row.type.replace("|", "\\|"),
        "yes" if row.required else "no",
        render_cell_constraints(row),
        row.default or "",
        desc,
    ]
    return "| " + " | ".join(cells) + " |"


def table(rows: list[Row]) -> str:
    return HEADER + "\n" + "\n".join(render_row(r) for r in rows)


def top_key(path: str) -> str:
    return re.split(r"[.\[]", path, maxsplit=1)[0]


def second_key(path: str) -> str | None:
    """`exposes[].binding.location.path` -> `exposes[].binding`; None for a top-level row."""
    segments = path.split(".")
    if len(segments) < 2:
        return None
    second = segments[1][:-2] if segments[1].endswith("[]") else segments[1]
    return f"{segments[0]}.{second}"


def ordered_top_keys(schema: dict[str, Any]) -> list[str]:
    required = list(schema.get("required", []))
    rest = [k for k in schema.get("properties", {}) if k not in required]
    return required + rest


SINGLES_HEADING = "Single-value fields"


def group_by_top(rows: list[Row]) -> dict[str, list[Row]]:
    by_top: dict[str, list[Row]] = {}
    for row in rows:
        by_top.setdefault(top_key(row.path), []).append(row)
    return by_top


def render_sections(schema: dict[str, Any], rows: list[Row], level_offset: int = 2) -> list[str]:
    """Single-row top-level fields share one table; the rest get a section each."""
    h2 = "#" * level_offset
    h3 = "#" * (level_offset + 1)
    out: list[str] = []
    by_top = group_by_top(rows)
    keys = [k for k in ordered_top_keys(schema) if by_top.get(k)]
    singles = [r for k in keys if len(by_top[k]) == 1 for r in by_top[k]]
    if singles:
        out.append(f"{h2} {SINGLES_HEADING}\n")
        out.append(table(singles) + "\n")
    for key in keys:
        group = by_top[key]
        if len(group) == 1:
            continue
        out.append(f"{h2} {key}\n")
        if len(group) <= SPLIT_ROWS:
            out.append(table(group) + "\n")
            continue
        sizes: dict[str, int] = {}
        for row in group:
            sk = second_key(row.path)
            if sk is not None:
                sizes[sk] = sizes.get(sk, 0) + 1
        head = [r for r in group if second_key(r.path) is None or sizes[second_key(r.path)] == 1]
        if head:
            out.append(table(head) + "\n")
        seen: list[str] = []
        subgroups: dict[str, list[Row]] = {}
        for row in group:
            sk = second_key(row.path)
            if sk is None or sizes[sk] == 1:
                continue
            if sk not in subgroups:
                seen.append(sk)
            subgroups.setdefault(sk, []).append(row)
        for sk in seen:
            out.append(f"{h3} `{sk}`\n")
            out.append(table(subgroups[sk]) + "\n")
    return out


def overview_table(schema: dict[str, Any], rows: list[Row]) -> str:
    by_top = group_by_top(rows)
    tops = {r.path: r for r in rows if "." not in r.path and "[" not in r.path}
    lines = ["| Field | Type | Required |", "| --- | --- | --- |"]
    for key in ordered_top_keys(schema):
        row = tops.get(key)
        if row is None:
            continue
        target = _anchor(SINGLES_HEADING) if len(by_top[key]) == 1 else _anchor(key)
        lines.append(f"| [{code(key)}](#{target}) | {row.type} | {'yes' if row.required else 'no'} |")
    return "\n".join(lines)


def _anchor(text: str) -> str:
    return re.sub(r"[^a-z0-9_-]+", "-", text.lower()).strip("-")


def frontmatter(title: str, description: str) -> str:
    # JSON strings are valid YAML double-quoted scalars, so a colon in the text is safe.
    return (
        f"---\ntitle: {json.dumps(title, ensure_ascii=False)}\n"
        f"description: {json.dumps(description, ensure_ascii=False)}\n---\n\n{MARKER}\n"
    )


def source_line(src: Source, version: str, digest: str) -> str:
    return (
        f"Generated from `fluid_build/schemas/fluid-schema-{version}.json` in the "
        f"`{PACKAGE}` {src.cli_version} package (sha256 `{digest[:16]}`). "
        "It is the schema `fluid validate` checks a contract against, rendered without edits. "
        "To regenerate: `python scripts/gen_contract_reference.py`."
    )


HOW_TO_READ = (
    "Each table row is one field, addressed by its path from the contract root: "
    "`.` descends into an object, `[]` marks the items of a list, and `<key>` stands for any "
    "key of a map. **Required** means required inside its parent object; the parent can itself "
    "be optional. **Allowed values** lists the enum, pattern and range the schema enforces. "
    "An object typed plainly `object` rejects keys the schema does not list; `object (open)` "
    "accepts extra keys and `object (free-form)` has no listed keys. A row that begins "
    "\"Only when ...\" exists only under that condition. See [how to read this "
    "reference](./README.md#how-to-read-a-row)."
)


def render_stable(src: Source, version: str) -> str:
    schema, digest = load_schema(src, version)
    rows = Walker(schema).walk_root()
    title = f"Contract field reference, schema {version}"
    out = [
        frontmatter(title, f"The fields of the FLUID {version} contract schema (stable): path, type, required, allowed values, default and description."),
        f"# {title}\n",
        f"Status: **stable**. Schema {version} is the newest stable schema bundled with the CLI. "
        f"The newer {', '.join(src.previews)} schema is a preview; see the "
        + ", ".join(f"[{p} preview delta](./contract-{p}-preview.md)" for p in src.previews)
        + ".\n",
        source_line(src, version, digest) + "\n",
        HOW_TO_READ + "\n",
        "## Top-level fields\n",
        overview_table(schema, rows) + "\n",
    ]
    out.extend(render_sections(schema, rows))
    return "\n".join(out).rstrip("\n") + "\n"


def _diff_attr(old: Row, new: Row) -> list[tuple[str, str, str]]:
    changes: list[tuple[str, str, str]] = []
    a, b = old.signature(), new.signature()
    for name in a:
        if a[name] == b[name]:
            continue
        changes.append((name, _fmt_attr(name, a[name]), _fmt_attr(name, b[name])))
    return changes


def _fmt_attr(name: str, value: Any) -> str:
    if name == "required":
        return "yes" if value else "no"
    if name == "allowed values":
        return "<br>".join(value) if value else "none"
    if name == "description":
        return prose(value) if value else "none"
    return str(value) if value not in (None, "") else "none"


def render_preview(src: Source, stable: str, preview: str) -> str:
    old_schema, _ = load_schema(src, stable)
    new_schema, digest = load_schema(src, preview)
    old_rows = Walker(old_schema).walk_root()
    new_walker = Walker(new_schema)
    new_rows = new_walker.walk_root()
    old_by = {r.key: r for r in old_rows}
    new_by = {r.key: r for r in new_rows}
    added = [r for r in new_rows if r.key not in old_by]
    removed = [r for r in old_rows if r.key not in new_by]
    changed = [(old_by[r.key], r) for r in new_rows if r.key in old_by and _diff_attr(old_by[r.key], r)]

    title = f"Contract field reference, schema {preview} preview"
    out = [
        frontmatter(title, f"What the FLUID {preview} preview schema adds to, and changes in, the stable {stable} schema, field by field."),
        f"# {title}\n",
        f"Status: **preview**. A contract opts in with `fluidVersion: \"{preview}\"`; a contract that declares {stable} is unaffected. "
        f"This page lists the difference between the {stable} schema and the {preview} schema as bundled with the CLI: "
        f"added fields, fields whose definition changed, and fields removed. A field not listed here has the same type, "
        f"required flag, allowed values, default and description in both; for those, use the "
        f"[{stable} reference](./contract-{stable}.md). A definition used at several paths is listed once, at its first path.\n",
        source_line(src, preview, digest) + "\n",
        HOW_TO_READ + "\n",
        "## At a glance\n",
        f"- Added: {len(added)} {'row' if len(added) == 1 else 'rows'}\n"
        f"- Changed: {len(changed)} {'row' if len(changed) == 1 else 'rows'}\n"
        f"- Removed: {len(removed)} {'row' if len(removed) == 1 else 'rows'}\n",
    ]
    # Added
    out.append("## Added fields\n")
    if added:
        by_top: dict[str, list[Row]] = {}
        for r in added:
            by_top.setdefault(top_key(r.path), []).append(r)
        for key in ordered_top_keys(new_schema):
            if key in by_top:
                out.append(f"### {key}\n")
                out.append(table(by_top[key]) + "\n")
    else:
        out.append("None.\n")
    # Changed
    out.append("## Changed fields\n")
    if changed:
        out.append(
            "Each row names the attribute that differs and shows both values.\n"
        )
        cl = ["| Path | Attribute | " + stable + " | " + preview + " |", "| --- | --- | --- | --- |"]
        for old, new in changed:
            label = code(new.path) + (f" (only when {new.when})" if new.when else "")
            for attr, before, after in _diff_attr(old, new):
                cl.append(f"| {label} | {attr} | {before} | {after} |")
        out.append("\n".join(cl) + "\n")
    else:
        out.append("None.\n")
    # Removed
    out.append("## Removed fields\n")
    if removed:
        out.append("\n".join(f"- {code(r.path)}" for r in removed) + "\n")
    else:
        out.append(f"None. Every {stable} field path is present in {preview}.\n")
    return "\n".join(out).rstrip("\n") + "\n"


# --------------------------------------------------------------------------- #
# Driver
# --------------------------------------------------------------------------- #


def expected_pages(src: Source) -> dict[str, str]:
    pages = {f"contract-{src.stable}.md": render_stable(src, src.stable)}
    for preview in src.previews:
        pages[f"contract-{preview}-preview.md"] = render_preview(src, src.stable, preview)
    return pages


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--check", action="store_true", help="write nothing; exit 1 if committed pages differ")
    ap.add_argument("--out-dir", type=Path, default=DEFAULT_OUT_DIR)
    args = ap.parse_args(argv)

    src = load_source()
    pages = expected_pages(src)
    out_dir: Path = args.out_dir

    if args.check:
        problems = 0
        for name, text in pages.items():
            path = out_dir / name
            if not path.exists():
                print(f"MISSING: {path.relative_to(REPO_ROOT) if path.is_relative_to(REPO_ROOT) else path}", file=sys.stderr)
                problems += 1
                continue
            have = path.read_text(encoding="utf-8")
            if have != text:
                problems += 1
                print(f"DRIFT: {path.name} differs from what the installed CLI generates", file=sys.stderr)
                diff = difflib.unified_diff(
                    have.splitlines(), text.splitlines(), "committed", "generated", lineterm="", n=0
                )
                for i, line in enumerate(diff):
                    if i >= 20:
                        print("  ...", file=sys.stderr)
                        break
                    print("  " + line[:200], file=sys.stderr)
        if out_dir.is_dir():
            for path in sorted(out_dir.glob("*.md")):
                if path.name in pages:
                    continue
                if MARKER in path.read_text(encoding="utf-8"):
                    print(f"STALE: {path.name} carries the generated marker but is no longer produced", file=sys.stderr)
                    problems += 1
        if problems:
            print(
                f"FAIL: {problems} reference page problem(s). Run "
                "`python scripts/gen_contract_reference.py` with the pinned CLI and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {len(pages)} generated reference pages match the schemas bundled in {PACKAGE} {src.cli_version}.")
        return 0

    out_dir.mkdir(parents=True, exist_ok=True)
    for path in sorted(out_dir.glob("*.md")):
        if path.name not in pages and MARKER in path.read_text(encoding="utf-8"):
            path.unlink()
            print(f"removed stale {path.name}")
    for name, text in pages.items():
        path = out_dir / name
        path.write_text(text, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(REPO_ROOT) if path.is_relative_to(REPO_ROOT) else path} ({len(text.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
